# -*- coding: utf-8 -*-
"""016 ac 2 prime lab ac 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5Xxm-yFJMYca__z5ne3zSeH-VnhFt94
"""

# Function to find GCD
def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a


# Input
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

# Output
print("GCD of", a, "and", b, ":", gcd(a, b))