# -*- coding: utf-8 -*-
"""016 ac 3lab ac 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5Xxm-yFJMYca__z5ne3zSeH-VnhFt94
"""

def diffie_hellman():
    p = int(input("Enter prime number p: "))
    g = int(input("Enter primitive root g: "))
    a = int(input("Enter Alice private key: "))
    b = int(input("Enter Bob private key: "))

    print("Public prime (p):", p)
    print("Public base (g):", g)

    # Public values
    A = pow(g, a, p)
    B = pow(g, b, p)

    print("Alice sends:", A)
    print("Bob sends:", B)

    # Shared secret
    secret_A = pow(B, a, p)
    secret_B = pow(A, b, p)

    print("Alice's secret:", secret_A)
    print("Bob's secret:", secret_B)

    if secret_A == secret_B:
        print("Shared key established successfully!")
    else:
        print("Key exchange failed!")


# Run function
diffie_hellman()