# -*- coding: utf-8 -*-
"""016 ac 1 prime lab ac 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5Xxm-yFJMYca__z5ne3zSeH-VnhFt94
"""

# Function to check prime
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True


# Function to generate primes
def generate_primes(limit):
    primes = []
    for i in range(2, limit + 1):
        if is_prime(i):
            primes.append(i)
    return primes


# Input
limit = int(input("Enter the limit: "))

# Output
print("Primes up to", limit, ":", generate_primes(limit))