# -*- coding: utf-8 -*-
"""016 ac 2.2prime lab ac 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5Xxm-yFJMYca__z5ne3zSeH-VnhFt94
"""

class MultiplicativeGroup:

    def __init__(self, n):
        self.n = n

    def operation(self, a, b):
        return (a * b) % self.n


# Input
n = int(input("Enter n: "))
a = int(input("Enter a: "))
b = int(input("Enter b: "))

# Create object
group = MultiplicativeGroup(n)

# Output
print("Group operation result:", group.operation(a, b))