# -*- coding: utf-8 -*-
"""016 ac 1.3prime lab ac 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5Xxm-yFJMYca__z5ne3zSeH-VnhFt94
"""

# Function to find GCD
def gcd(a, b):
    while b != 0:
        a, b = b, a % b
    return a


# Function to calculate Euler's Phi
def euler_phi(n):
    count = 0
    for i in range(1, n):
        if gcd(i, n) == 1:
            count += 1
    return count


# Input
n = int(input("Enter the value of n: "))

# Output
print("Phi(", n, ") :", euler_phi(n))