# -*- coding: utf-8 -*-
"""016 ac 2.3prime lab ac 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5Xxm-yFJMYca__z5ne3zSeH-VnhFt94
"""

class RingZn:

    def __init__(self, n):
        self.n = n

    def add(self, a, b):
        return (a + b) % self.n

    def mul(self, a, b):
        return (a * b) % self.n


# Input
n = int(input("Enter n: "))
a = int(input("Enter a: "))
b = int(input("Enter b: "))

# Create object
ring = RingZn(n)

# Output
print("Ring addition:", ring.add(a, b))
print("Ring multiplication:", ring.mul(a, b))