# -*- coding: utf-8 -*-
"""016 ac 2.1prime lab ac 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-5Xxm-yFJMYca__z5ne3zSeH-VnhFt94
"""

# Modular addition
def mod_add(a, b, m):
    return (a + b) % m


# Modular subtraction
def mod_sub(a, b, m):
    return (a - b) % m


# Modular multiplication
def mod_mul(a, b, m):
    return (a * b) % m


# Modular exponentiation
def mod_exp(base, exp, m):
    return pow(base, exp, m)   # built-in fast power


# Input
a = int(input("Enter a: "))
b = int(input("Enter b: "))
m = int(input("Enter modulus m: "))

# Output
print("Modular addition:", mod_add(a, b, m))
print("Modular subtraction:", mod_sub(a, b, m))
print("Modular multiplication:", mod_mul(a, b, m))
print("Modular exponent:", mod_exp(a, b, m))